# Generated by Django 3.0.5 on 2020-04-30 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('numero_telefono', models.CharField(max_length=60)),
                ('estado_civil', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('lugar_procedencia', models.CharField(max_length=60)),
                ('sobre_mi', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
