# Generated by Django 3.0.5 on 2020-05-02 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias_chica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=60)),
                ('direccion_servicio', models.TextField()),
                ('tarifa', models.CharField(max_length=60)),
                ('bitacora_servicio', models.TextField(default='No hay problemas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
