# Generated by Django 3.0.5 on 2020-05-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicas', '0002_chica_imagen_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chica',
            name='imagen_profile',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
