# Generated by Django 3.0.5 on 2020-05-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicas', '0003_auto_20200501_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chica',
            name='imagen_profile',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
