# Generated by Django 3.0.5 on 2020-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicas', '0004_auto_20200501_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='chica',
            name='imagen_segunda',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='chica',
            name='imagen_tercera',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
